services:
  logestoque:
    build:
      context: .
      dockerfile: dockerfile
    container_name: logestoque
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 4004
    ports:
      - "4004:4004"
    volumes:
      - logestoque-data:/app/gen/srv/db

volumes:
  logestoque-data:
